# -*- coding: utf-8 -*-
"""Titanic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E_leVizObM__0GnAdXgyDNyjDHwVLQjQ
"""

# Titanic EDA Assignment - Internship Task 5

# 📘 1. Introduction
# Titanic Dataset Analysis
# Goal: Explore patterns in survival based on class, gender, age, etc.

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
df = pd.read_csv("train (1).csv")

# 📊 2. Data Overview
print(df.info())
print(df.describe())
print(df.isnull().sum())

# 🔧 3. Data Cleaning
# Fill Age with median
df['Age'].fillna(df['Age'].median(), inplace=True)
# Fill Embarked with mode
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)
# Drop Cabin (too many missing values)
df.drop(columns=['Cabin'], inplace=True)

# 👨‍👩‍👧 4. Feature Engineering
# FamilySize = SibSp + Parch + 1
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1
# Extract Title from Name
df['Title'] = df['Name'].apply(lambda name: name.split(',')[1].split('.')[0].strip())
rare_titles = df['Title'].value_counts()[df['Title'].value_counts() < 10].index
df['Title'] = df['Title'].replace(rare_titles, 'Rare')

# 📊 5. Univariate Analysis
sns.countplot(x='Survived', data=df)
plt.title("Survival Count")
plt.show()

sns.histplot(df['Age'], kde=True)
plt.title("Age Distribution")
plt.show()

# 📈 6. Bivariate Analysis
sns.boxplot(x='Survived', y='Age', data=df)
plt.title("Age vs Survival")
plt.show()

sns.barplot(x='Pclass', y='Survived', data=df)
plt.title("Class vs Survival Rate")
plt.show()

sns.countplot(x='Sex', hue='Survived', data=df)
plt.title("Survival by Gender")
plt.show()

# 🔗 7. Multivariate Analysis
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

sns.pairplot(df[['Survived', 'Pclass', 'Age', 'Fare']])
plt.suptitle("Pairplot of Key Variables", y=1.02)
plt.show()

# 📋 8. Summary of Insights
# 1. Women had a much higher survival rate.
# 2. First-class passengers had better chances of survival.
# 3. Younger passengers were more likely to survive.
# 4. Family size had an impact on survival (too large/small groups affected).
# 5. Titles like 'Mrs', 'Miss' had higher survival due to gender and age.

# 📘 9. Conclusion
# This analysis highlighted that gender, class, and age strongly influenced survival.
# Insights can guide disaster planning and prioritization in emergencies.

# End of Notebook

